name: Build Firmware

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Safe Directory
        run: git config --global --add safe.directory $(pwd)

      - name: Build Firmware
        run: |
          qmk compile -kb onekey_rp2040 -km vial

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onekey_rp2040_firmware
          path: |
            *.uf2
            .build/*.uf2
