name: Build QMK Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile Firmware
        run: |
          qmk compile -kb onekey_rp2040 -km default

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onekey_rp2040_firmware
          path: |
            *.uf2
            *.bin
            *.hex
